In [4]:
#AES Encryption
import numpy as np
plain = input("Plain Text of 128bits(16 characters):")
k0 = input("Key of 128bits(16 characters): ")
#plain = "amartya   raghav"
#k0 = "implementing aes"
key = ['']*len(k0)

def inverse(n):    
    for d in range(0,26):
        inv=0
        if(d*n)%26==1:
            inv=d
        return inv

w = np.zeros([4,4],dtype=int)
p = np.zeros([4,4],dtype=int)
a = np.zeros([4,4],dtype=int)
b = np.zeros([4,4],dtype=int)
c = np.zeros([4,4],dtype=int)
k = np.zeros([1,4],dtype=int)
m =[[int('02',16),int('03',16),int('01',16),int('01',16)],[int('01',16),int('02',16),int('03',16),int('01',16)],[int('01',16),int('01',16),int('02',16),int('03',16)],[int('03',16),int('01',16),int('01',16),int('02',16)]]
rc=[int('01',16),int('02',16),int('04',16),int('08',16),int('10',16),int('20',16),int('40',16),int('80',16),int('1b',16),int('36',16)]
sbox = [
        0x63, 0x7c, 0x77, 0x7b, 0xf2, 0x6b, 0x6f, 0xc5, 0x30, 0x01, 0x67, 0x2b, 0xfe, 0xd7, 0xab, 0x76,
        0xca, 0x82, 0xc9, 0x7d, 0xfa, 0x59, 0x47, 0xf0, 0xad, 0xd4, 0xa2, 0xaf, 0x9c, 0xa4, 0x72, 0xc0,
        0xb7, 0xfd, 0x93, 0x26, 0x36, 0x3f, 0xf7, 0xcc, 0x34, 0xa5, 0xe5, 0xf1, 0x71, 0xd8, 0x31, 0x15,
        0x04, 0xc7, 0x23, 0xc3, 0x18, 0x96, 0x05, 0x9a, 0x07, 0x12, 0x80, 0xe2, 0xeb, 0x27, 0xb2, 0x75,
        0x09, 0x83, 0x2c, 0x1a, 0x1b, 0x6e, 0x5a, 0xa0, 0x52, 0x3b, 0xd6, 0xb3, 0x29, 0xe3, 0x2f, 0x84,
        0x53, 0xd1, 0x00, 0xed, 0x20, 0xfc, 0xb1, 0x5b, 0x6a, 0xcb, 0xbe, 0x39, 0x4a, 0x4c, 0x58, 0xcf,
        0xd0, 0xef, 0xaa, 0xfb, 0x43, 0x4d, 0x33, 0x85, 0x45, 0xf9, 0x02, 0x7f, 0x50, 0x3c, 0x9f, 0xa8,
        0x51, 0xa3, 0x40, 0x8f, 0x92, 0x9d, 0x38, 0xf5, 0xbc, 0xb6, 0xda, 0x21, 0x10, 0xff, 0xf3, 0xd2,
        0xcd, 0x0c, 0x13, 0xec, 0x5f, 0x97, 0x44, 0x17, 0xc4, 0xa7, 0x7e, 0x3d, 0x64, 0x5d, 0x19, 0x73,
        0x60, 0x81, 0x4f, 0xdc, 0x22, 0x2a, 0x90, 0x88, 0x46, 0xee, 0xb8, 0x14, 0xde, 0x5e, 0x0b, 0xdb,
        0xe0, 0x32, 0x3a, 0x0a, 0x49, 0x06, 0x24, 0x5c, 0xc2, 0xd3, 0xac, 0x62, 0x91, 0x95, 0xe4, 0x79,
        0xe7, 0xc8, 0x37, 0x6d, 0x8d, 0xd5, 0x4e, 0xa9, 0x6c, 0x56, 0xf4, 0xea, 0x65, 0x7a, 0xae, 0x08,
        0xba, 0x78, 0x25, 0x2e, 0x1c, 0xa6, 0xb4, 0xc6, 0xe8, 0xdd, 0x74, 0x1f, 0x4b, 0xbd, 0x8b, 0x8a,
        0x70, 0x3e, 0xb5, 0x66, 0x48, 0x03, 0xf6, 0x0e, 0x61, 0x35, 0x57, 0xb9, 0x86, 0xc1, 0x1d, 0x9e,
        0xe1, 0xf8, 0x98, 0x11, 0x69, 0xd9, 0x8e, 0x94, 0x9b, 0x1e, 0x87, 0xe9, 0xce, 0x55, 0x28, 0xdf,
        0x8c, 0xa1, 0x89, 0x0d, 0xbf, 0xe6, 0x42, 0x68, 0x41, 0x99, 0x2d, 0x0f, 0xb0, 0x54, 0xbb, 0x16
        ]

sboxInv = [
        0x52, 0x09, 0x6a, 0xd5, 0x30, 0x36, 0xa5, 0x38, 0xbf, 0x40, 0xa3, 0x9e, 0x81, 0xf3, 0xd7, 0xfb,
        0x7c, 0xe3, 0x39, 0x82, 0x9b, 0x2f, 0xff, 0x87, 0x34, 0x8e, 0x43, 0x44, 0xc4, 0xde, 0xe9, 0xcb,
        0x54, 0x7b, 0x94, 0x32, 0xa6, 0xc2, 0x23, 0x3d, 0xee, 0x4c, 0x95, 0x0b, 0x42, 0xfa, 0xc3, 0x4e,
        0x08, 0x2e, 0xa1, 0x66, 0x28, 0xd9, 0x24, 0xb2, 0x76, 0x5b, 0xa2, 0x49, 0x6d, 0x8b, 0xd1, 0x25,
        0x72, 0xf8, 0xf6, 0x64, 0x86, 0x68, 0x98, 0x16, 0xd4, 0xa4, 0x5c, 0xcc, 0x5d, 0x65, 0xb6, 0x92,
        0x6c, 0x70, 0x48, 0x50, 0xfd, 0xed, 0xb9, 0xda, 0x5e, 0x15, 0x46, 0x57, 0xa7, 0x8d, 0x9d, 0x84,
        0x90, 0xd8, 0xab, 0x00, 0x8c, 0xbc, 0xd3, 0x0a, 0xf7, 0xe4, 0x58, 0x05, 0xb8, 0xb3, 0x45, 0x06,
        0xd0, 0x2c, 0x1e, 0x8f, 0xca, 0x3f, 0x0f, 0x02, 0xc1, 0xaf, 0xbd, 0x03, 0x01, 0x13, 0x8a, 0x6b,
        0x3a, 0x91, 0x11, 0x41, 0x4f, 0x67, 0xdc, 0xea, 0x97, 0xf2, 0xcf, 0xce, 0xf0, 0xb4, 0xe6, 0x73,
        0x96, 0xac, 0x74, 0x22, 0xe7, 0xad, 0x35, 0x85, 0xe2, 0xf9, 0x37, 0xe8, 0x1c, 0x75, 0xdf, 0x6e,
        0x47, 0xf1, 0x1a, 0x71, 0x1d, 0x29, 0xc5, 0x89, 0x6f, 0xb7, 0x62, 0x0e, 0xaa, 0x18, 0xbe, 0x1b,
        0xfc, 0x56, 0x3e, 0x4b, 0xc6, 0xd2, 0x79, 0x20, 0x9a, 0xdb, 0xc0, 0xfe, 0x78, 0xcd, 0x5a, 0xf4,
        0x1f, 0xdd, 0xa8, 0x33, 0x88, 0x07, 0xc7, 0x31, 0xb1, 0x12, 0x10, 0x59, 0x27, 0x80, 0xec, 0x5f,
        0x60, 0x51, 0x7f, 0xa9, 0x19, 0xb5, 0x4a, 0x0d, 0x2d, 0xe5, 0x7a, 0x9f, 0x93, 0xc9, 0x9c, 0xef,
        0xa0, 0xe0, 0x3b, 0x4d, 0xae, 0x2a, 0xf5, 0xb0, 0xc8, 0xeb, 0xbb, 0x3c, 0x83, 0x53, 0x99, 0x61,
        0x17, 0x2b, 0x04, 0x7e, 0xba, 0x77, 0xd6, 0x26, 0xe1, 0x69, 0x14, 0x63, 0x55, 0x21, 0x0c, 0x7d
        ]

cipher=""
#print(m)
z=0
for y in range(4):
    for x in range(4):
        p[x][y]= (ord(plain[z]))
        w[x][y]= (ord(k0[z]))
        #print(w)
        z+=1
print("plain text:")
print(p)
print("R0 Key:")
print(w)
#print(int(w[0][1],16))#converting back to decimal
#Addition of first round key
a=np.bitwise_xor(p,w)
print("A matrix:")
print(a)
#Round starts
for i in range(10):
#Byte Substitution - Needs correction
    for z in range(4):
        for y in range(4):
            b[y][z]= inverse(a[y][z])
   # print(b)
#Shift Rows
    b=a # must be changed to b after correction in byte substitution
#print(c)
    b[1]=np.roll(b[1],-1)
    b[2]=np.roll(b[2],-2)
    b[3]=np.roll(b[3],-3)
    print("After Shift rows:")
    print(b)
#Mix Columns- not in last round
    if i<9:
        c=np.multiply(m,b)
        print("After Mix Columns:")
        print(c)
#Key Generation
    #gfunction
    for l in range(4):
        #for m in range(4):
        k=np.roll(w[l],-1)
            #for h in range(4):
             #   for f in range(4):
              #      k[f]=inverse(k[f])   #Needs correction for Shift box inverse value 
        k=np.bitwise_xor(k,[rc[i],0,0,0])
        #print("gfunction output for round %d:" %(i+1)) 
        #print(k)
        w[l]=np.bitwise_xor(w[l],k)
    print("Key after round %d" %(i+1))
    print(w)
#Add Key
    a=np.bitwise_xor(c,w)
    print("result after round %d" %(i+1))
    print(a)
#Converting to cipher text
for k in range(4):
    for t in range(4):
        cipher+=chr((a[t][k])%26+65)
print("Cipher Text:")
print(cipher)


Plain Text of 128bits(16 characters):oksoyouwereright
Key of 128bits(16 characters): oksoyouwerewrong
plain text:
[[111 121 101 105]
 [107 111 114 103]
 [115 117 101 104]
 [111 119 114 116]]
R0 Key:
[[111 121 101 114]
 [107 111 114 111]
 [115 117 101 110]
 [111 119 119 103]]
A matrix:
[[ 0  0  0 27]
 [ 0  0  0  8]
 [ 0  0  0  6]
 [ 0  0  5 19]]
After Shift rows:
[[ 0  0  0 27]
 [ 0  0  8  0]
 [ 0  6  0  0]
 [19  0  0  5]]
After Mix Columns:
[[ 0  0  0 27]
 [ 0  0 24  0]
 [ 0  6  0  0]
 [57  0  0 10]]
Key after round 1
[[23 28 23 29]
 [ 5 29 29  4]
 [ 7 16 11 29]
 [25  0 16  8]]
result after round 1
[[23 28 23  6]
 [ 5 29  5  4]
 [ 7 22 11 29]
 [32  0 16  2]]
After Shift rows:
[[23 28 23  6]
 [29  5  4  5]
 [11 29  7 22]
 [ 2 32  0 16]]
After Mix Columns:
[[46 84 23  6]
 [29 10 12  5]
 [11 29 14 66]
 [ 6 32  0 32]]
Key after round 2
[[ 9 11 10 10]
 [26  0 25  1]
 [21 27 22 26]
 [27 16 24 17]]
result after round 2
[[39 95 29 12]
 [ 7 10 21  4]
 [30  6 24 88]
 [29 48 24 49]]
After Shift r

In [82]:
dec = 255
h =hex(dec)
print(type(h))
print(h)

print(int(h,16))

<class 'str'>
0xff
255


In [139]:
print(hex(int('0x74',16)^int('0x69',16)))
print(inverse(8))


0x1d
0
