In [12]:
import numpy as np
public = input("Plain Text: ")
ciparr =[]
cipher =""
key = input("Key of length 9: ")
result =[[0],[0],[0]]
#Key Matrix
arr = np.zeros([3,3],dtype= int)
pubarr = np.zeros([3,1],dtype=int)
k= 0
for i in range(3):
    for j in range(3):
        arr[i][j] = (ord(key[k])-97)%26
        k+= 1
print(arr)
det = int(np.linalg.det(arr).round(2))
if(det==0 or det== 13 or det%2==0):
    print("Inverse of matrix does not exist. Choose another matrix")
#Encryption
for i in range(0,len(public),3):
    if(i<len(public)-2):
        pubarr = np.array([[(ord(public[i])-97)%26],[(ord(public[i+1])-97)%26],[(ord(public[i+2])-97)%26]])
    elif(i<len(public)-1):
        pubarr = np.array([[(ord(public[i])-97)%26],[(ord(public[i+1])-97)%26],[(ord("x")-97)%26]])
    else:
        pubarr = np.array([[(ord(public[i])-97)%26],[(ord("x")-97)%26],[(ord("x")-97)%26]])
        
    ciparr = np.dot(arr,pubarr)
    for j in range(0,3,1):
        ciparr[j][0]=(ciparr[j][0]%26)+97
        cipher +=chr(ciparr[j]) 
print(cipher.upper())




Plain Text: hello
Key of length 9: alphabeta
[[ 0 11 15]
 [ 7  0  1]
 [ 4 19  0]]
BIAFWY


In [13]:
#Decryption
arrinv = np.zeros([3,3],dtype= int)
dinv=0
det = int(np.linalg.det(arr).round(2))
for i in range(0,26):
    if (i*det)%26==1:
        dinv=i
arrinv = np.linalg.inv(arr)
arrinv = (det*arrinv)%26 #Adjoint
arrinv = (dinv*arrinv)%26
print(arrinv)
decipher=""

decarr =[]
for k in range(0,len(public),3):
    decarr = np.array([[(ord(cipher[k])-97)%26],[(ord(cipher[k+1])-97)%26],[(ord(cipher[k+2])-97)%26]])    
    decarr = np.dot(arrinv,decarr)%26
    for y in range(0,3):
        decarr[y][0]=decarr[y][0].round()
    for i in decarr:
        z = chr(i+97)
        if z=="{":
            z='a'
        decipher+= z
temp = list(decipher)
for l in range(len(decipher)-1,0,-1):
    if temp[l] == 'x':
        temp.pop()
    else:
        break
decipher =""
for m in temp:
    decipher+=m 
print(decipher)
    


[[ 3.  7.  1.]
 [24.  4. 19.]
 [ 5.  4. 19.]]
hello


In [88]:
print(chr(2+97))
print(chr(4+97))
print(chr(5+97))
print(chr(9+97))
print(chr(2+97))
print(chr(1+97))
print(chr(3+97))
print(chr(17+97))
print(chr(7+97))
#cefjcbdrh

c
e
f
j
c
b
d
r
h
19


In [23]:
import numpy as np
arr1 =[[6,24,1],[13,16,10],[20,17,15]]
a1 = np.linalg.inv(arr1)
print(a1)
det1 = np.linalg.det(arr1)
print(det1)
a1 = (det1*a1)
print(a1)

[[ 0.15873016 -0.77777778  0.50793651]
 [ 0.01133787  0.15873016 -0.10657596]
 [-0.2244898   0.85714286 -0.48979592]]
441.0
[[  70. -343.  224.]
 [   5.   70.  -47.]
 [ -99.  378. -216.]]
